name: gorelease

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  gorelease:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        run: |
          echo "TZ=Asia/Tokyo" >> ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.2'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
